# permissions for end users to view qservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qservice-viewer-role
rules:
- apiGroups:
  - apps.tech
  resources:
  - qservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.tech
  resources:
  - qservices/status
  verbs:
  - get
