apiVersion: v1
kind: PersistentVolume
metadata:
  name: local
spec:
  storageClassName: manual
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /var/log/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-master-01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi